# Generated by Django 3.1.3 on 2020-11-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cmail', models.EmailField(max_length=254)),
                ('cphone', models.CharField(max_length=10)),
                ('cpassword', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('fmail', models.EmailField(max_length=254)),
                ('fphone', models.CharField(max_length=10)),
                ('fpassword', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'farmer',
            },
        ),
    ]
