# Generated by Django 3.1.3 on 2020-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('qty', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=10)),
                ('day', models.DateField()),
                ('product', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'myorders',
            },
        ),
    ]
