# Generated by Django 3.1.3 on 2020-11-27 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
